apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: mariatest
  name: sites
spec:
  ingressClassName: nginx 
  rules:
    - host: "jannegpriv123.crabdance.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: yagolangsite-service
                port:
                  number: 80
    - host: "jannegpriv123.chickenkiller.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: staticwebserver-service
                port:
                  number: 80
